const DEFAULT_MENU=[
['Classic Burger','Fast Food','Rs. 450','Juicy chicken patty, crisp lettuce and house sauce.','https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=900&q=90'],
['Zinger Burger','Fast Food','Rs. 550','Crispy zinger fillet, cheese, lettuce and signature sauce.','https://images.unsplash.com/photo-1606755962773-d324e0a13086?auto=format&fit=crop&w=900&q=90'],
['Chicken Pizza','Fast Food','Rs. 850','Cheesy chicken pizza loaded with tender chicken and herbs.','https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=900&q=90'],
['Chicken Shawarma','Fast Food','Rs. 350','Tender spiced chicken, garlic sauce and fresh salad in warm pita.','https://images.unsplash.com/photo-1529006557810-274b9b2fc783?auto=format&fit=crop&w=900&q=90'],
['Fries','Fast Food','Rs. 250','Crispy golden fries with house dip.','https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=900&q=90'],
['Club Sandwich','Fast Food','Rs. 550','Triple-layer chicken sandwich with fresh salad and sauce.','https://images.unsplash.com/photo-1553909489-cd47e0907980?auto=format&fit=crop&w=900&q=90'],
['Chicken Tikka','BBQ','Rs. 450','Charcoal-grilled spiced chicken tikka with chutney and lemon.','https://commons.wikimedia.org/wiki/Special:Redirect/file/Chicken_Tikka.jpg'],
['Malai Boti','BBQ','Rs. 600','Tender creamy chicken boti grilled until golden and smoky.','https://commons.wikimedia.org/wiki/Special:Redirect/file/Malai_Boti.JPG'],
['Seekh Kebab','BBQ','Rs. 550','Juicy spiced seekh kebabs grilled over charcoal.','https://commons.wikimedia.org/wiki/Special:Redirect/file/Seekh_Kebabs.jpg'],
['Chicken Wings','BBQ','Rs. 550','Smoky grilled wings with a bold glazed finish.','https://commons.wikimedia.org/wiki/Special:Redirect/file/Chicken_wings_as_food.jpg'],
['BBQ Platters','BBQ','Rs. 1,350','A shareable BBQ spread with grilled chicken, skewers and sides.','https://commons.wikimedia.org/wiki/Special:Redirect/file/Tandoori_platter.jpg'],
['Gulab Jamun','Sweets','Rs. 220','Soft golden gulab jamun soaked in fragrant syrup.','https://commons.wikimedia.org/wiki/Special:Redirect/file/Gulab_Jaamun20140206233003.JPG'],
['Rasmalai','Sweets','Rs. 280','Soft cheese dumplings in chilled saffron milk.','https://images.unsplash.com/photo-1605197161470-d0261cac6767?auto=format&fit=crop&w=900&q=90'],
['Kheer','Sweets','Rs. 250','Creamy rice kheer finished with almonds and pistachios.','https://commons.wikimedia.org/wiki/Special:Redirect/file/Kheer.jpg'],
['Brownies','Sweets','Rs. 300','Rich fudgy chocolate brownies with a crackly top.','https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=900&q=90'],
['Ice Cream','Desserts','Rs. 250','Cool creamy scoops with your choice of topping.','https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?auto=format&fit=crop&w=900&q=90'],
['Chocolate Lava Cake','Desserts','Rs. 450','Warm chocolate lava cake with a molten center.','https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=900&q=90'],
['Cheesecake','Desserts','Rs. 500','Silky cheesecake on a buttery biscuit base.','https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&w=900&q=90'],
['Waffles','Desserts','Rs. 450','Golden waffles with cream and chocolate drizzle.','https://images.unsplash.com/photo-1562376552-7684c019e1cb?auto=format&fit=crop&w=900&q=90'],
['Sundaes','Desserts','Rs. 350','Vanilla ice cream, chocolate sauce and crunchy toppings.','https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=900&q=90']
];
const DEFAULT_DEALS=[
['Mehfil Deal','2 Zinger Burgers · Large Fries · 2 Drinks','Rs. 899','DEAL 01',false,'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=1000&q=90'],
['BBQ Feast','Tikka · Malai Boti · Seekh Kebab · 2 Naan · Salad','Rs. 1,499','DEAL 02',true,'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?auto=format&fit=crop&w=1000&q=90'],
['Family Mehfil','4 Burgers · 2 Loaded Fries · 12 Wings · 4 Drinks','Rs. 2,799','DEAL 03',false,'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=1000&q=90'],
['Meetha Feast','Brownie · 2 Ice Creams · Waffles · Lava Cake','Rs. 999','DEAL 04',false,'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=1000&q=90']
];

module.exports=function setupContentApi(app,pool,requireAdmin,upload){
  const db=()=>Boolean(process.env.DATABASE_URL);
  async function ensure(){
    if(!db()) return;
    await pool.query(`CREATE TABLE IF NOT EXISTS menu_items(
      id SERIAL PRIMARY KEY,name TEXT NOT NULL,category TEXT NOT NULL,price TEXT NOT NULL DEFAULT '',description TEXT NOT NULL DEFAULT '',image_url TEXT, image_data BYTEA,mime_type TEXT,visible BOOLEAN NOT NULL DEFAULT TRUE,sort_order INTEGER NOT NULL DEFAULT 100,updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await pool.query(`CREATE TABLE IF NOT EXISTS deals(
      id SERIAL PRIMARY KEY,name TEXT NOT NULL,items TEXT NOT NULL DEFAULT '',price TEXT NOT NULL DEFAULT '',badge TEXT NOT NULL DEFAULT '',featured BOOLEAN NOT NULL DEFAULT FALSE,image_url TEXT,image_data BYTEA,mime_type TEXT,visible BOOLEAN NOT NULL DEFAULT TRUE,sort_order INTEGER NOT NULL DEFAULT 100,updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    const mc=await pool.query('SELECT COUNT(*)::int AS n FROM menu_items');
    if(mc.rows[0].n===0){for(let i=0;i<DEFAULT_MENU.length;i++){const x=DEFAULT_MENU[i];await pool.query('INSERT INTO menu_items(name,category,price,description,image_url,sort_order) VALUES($1,$2,$3,$4,$5,$6)',[...x,i+1]);}}
    const dc=await pool.query('SELECT COUNT(*)::int AS n FROM deals');
    if(dc.rows[0].n===0){for(let i=0;i<DEFAULT_DEALS.length;i++){const x=DEFAULT_DEALS[i];await pool.query('INSERT INTO deals(name,items,price,badge,featured,image_url,sort_order) VALUES($1,$2,$3,$4,$5,$6,$7)',[...x,i+1]);}}
  }
  const ready=ensure().catch(e=>console.error('content setup',e));
  const imageUrl=(kind,r)=>r.image_data?`/api/${kind}-image/${r.id}?v=${new Date(r.updated_at).getTime()}`:(r.image_url||'');
  app.get('/api/menu-items',async(req,res)=>{try{await ready;if(!db())return res.json([]);const {rows}=await pool.query('SELECT * FROM menu_items WHERE visible=TRUE ORDER BY sort_order,id');res.json(rows.map(r=>({id:r.id,name:r.name,category:r.category,price:r.price,description:r.description,visible:r.visible,sortOrder:r.sort_order,imageUrl:imageUrl('menu-item',r)})));}catch(e){res.status(500).json({error:'Could not load menu'});}});
  app.get('/api/admin/menu-items',requireAdmin,async(req,res)=>{try{await ready;const {rows}=await pool.query('SELECT * FROM menu_items ORDER BY sort_order,id');res.json(rows.map(r=>({id:r.id,name:r.name,category:r.category,price:r.price,description:r.description,visible:r.visible,sortOrder:r.sort_order,imageUrl:imageUrl('menu-item',r)})));}catch(e){res.status(500).json({error:'Could not load menu'});}});
  app.get('/api/menu-item-image/:id',async(req,res)=>{try{const {rows}=await pool.query('SELECT image_data,mime_type FROM menu_items WHERE id=$1',[req.params.id]);if(!rows.length||!rows[0].image_data)return res.sendStatus(404);res.type(rows[0].mime_type||'image/jpeg').send(rows[0].image_data);}catch(e){res.sendStatus(404);}});
  app.post('/api/admin/menu-item',requireAdmin,upload.single('image'),async(req,res)=>{try{await ready;const id=Number(req.body.id)||null,name=String(req.body.name||'').trim().slice(0,120),category=String(req.body.category||'Fast Food').slice(0,40),price=String(req.body.price||'').slice(0,40),description=String(req.body.description||'').slice(0,400),visible=String(req.body.visible)!=='false',sortOrder=Math.max(1,Number(req.body.sortOrder)||100),imageUrlText=String(req.body.imageUrl||'').slice(0,1000);if(!name)return res.status(400).json({error:'Item name is required'});if(req.file&&!req.file.mimetype.startsWith('image/'))return res.status(400).json({error:'File must be an image'});if(id){if(req.file)await pool.query('UPDATE menu_items SET name=$1,category=$2,price=$3,description=$4,visible=$5,sort_order=$6,image_url=$7,image_data=$8,mime_type=$9,updated_at=NOW() WHERE id=$10',[name,category,price,description,visible,sortOrder,imageUrlText,req.file.buffer,req.file.mimetype,id]);else await pool.query('UPDATE menu_items SET name=$1,category=$2,price=$3,description=$4,visible=$5,sort_order=$6,image_url=CASE WHEN $7<>\'\' THEN $7 ELSE image_url END,updated_at=NOW() WHERE id=$8',[name,category,price,description,visible,sortOrder,imageUrlText,id]);res.json({ok:true,id});}else{const q=await pool.query('INSERT INTO menu_items(name,category,price,description,visible,sort_order,image_url,image_data,mime_type) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id',[name,category,price,description,visible,sortOrder,imageUrlText,req.file?req.file.buffer:null,req.file?req.file.mimetype:null]);res.json({ok:true,id:q.rows[0].id});}}catch(e){console.error(e);res.status(500).json({error:'Could not save menu item'});}});
  app.delete('/api/admin/menu-item/:id',requireAdmin,async(req,res)=>{try{await pool.query('DELETE FROM menu_items WHERE id=$1',[req.params.id]);res.json({ok:true});}catch(e){res.status(500).json({error:'Could not delete item'});}});
  app.get('/api/deals',async(req,res)=>{try{await ready;if(!db())return res.json([]);const {rows}=await pool.query('SELECT * FROM deals WHERE visible=TRUE ORDER BY sort_order,id');res.json(rows.map(r=>({id:r.id,name:r.name,items:r.items,price:r.price,badge:r.badge,featured:r.featured,visible:r.visible,sortOrder:r.sort_order,imageUrl:imageUrl('deal',r)})));}catch(e){res.status(500).json({error:'Could not load deals'});}});
  app.get('/api/admin/deals',requireAdmin,async(req,res)=>{try{await ready;const {rows}=await pool.query('SELECT * FROM deals ORDER BY sort_order,id');res.json(rows.map(r=>({id:r.id,name:r.name,items:r.items,price:r.price,badge:r.badge,featured:r.featured,visible:r.visible,sortOrder:r.sort_order,imageUrl:imageUrl('deal',r)})));}catch(e){res.status(500).json({error:'Could not load deals'});}});
  app.get('/api/deal-image/:id',async(req,res)=>{try{const {rows}=await pool.query('SELECT image_data,mime_type FROM deals WHERE id=$1',[req.params.id]);if(!rows.length||!rows[0].image_data)return res.sendStatus(404);res.type(rows[0].mime_type||'image/jpeg').send(rows[0].image_data);}catch(e){res.sendStatus(404);}});
  app.post('/api/admin/deal',requireAdmin,upload.single('image'),async(req,res)=>{try{await ready;const id=Number(req.body.id)||null,name=String(req.body.name||'').trim().slice(0,120),items=String(req.body.items||'').slice(0,500),price=String(req.body.price||'').slice(0,40),badge=String(req.body.badge||'').slice(0,60),featured=String(req.body.featured)==='true',visible=String(req.body.visible)!=='false',sortOrder=Math.max(1,Number(req.body.sortOrder)||100),imageUrlText=String(req.body.imageUrl||'').slice(0,1000);if(!name)return res.status(400).json({error:'Deal name is required'});if(req.file&&!req.file.mimetype.startsWith('image/'))return res.status(400).json({error:'File must be an image'});if(id){if(req.file)await pool.query('UPDATE deals SET name=$1,items=$2,price=$3,badge=$4,featured=$5,visible=$6,sort_order=$7,image_url=$8,image_data=$9,mime_type=$10,updated_at=NOW() WHERE id=$11',[name,items,price,badge,featured,visible,sortOrder,imageUrlText,req.file.buffer,req.file.mimetype,id]);else await pool.query('UPDATE deals SET name=$1,items=$2,price=$3,badge=$4,featured=$5,visible=$6,sort_order=$7,image_url=CASE WHEN $8<>\'\' THEN $8 ELSE image_url END,updated_at=NOW() WHERE id=$9',[name,items,price,badge,featured,visible,sortOrder,imageUrlText,id]);res.json({ok:true,id});}else{const q=await pool.query('INSERT INTO deals(name,items,price,badge,featured,visible,sort_order,image_url,image_data,mime_type) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING id',[name,items,price,badge,featured,visible,sortOrder,imageUrlText,req.file?req.file.buffer:null,req.file?req.file.mimetype:null]);res.json({ok:true,id:q.rows[0].id});}}catch(e){console.error(e);res.status(500).json({error:'Could not save deal'});}});
  app.delete('/api/admin/deal/:id',requireAdmin,async(req,res)=>{try{await pool.query('DELETE FROM deals WHERE id=$1',[req.params.id]);res.json({ok:true});}catch(e){res.status(500).json({error:'Could not delete deal'});}});
};
