const express=require('express');
const path=require('path');
const crypto=require('crypto');
const multer=require('multer');
const {Pool}=require('pg');
const app=express();
const port=process.env.PORT||3000;
const BUILD_VERSION='2026-08-31-admin-email-db-only-v1';
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL?{rejectUnauthorized:false}:false});
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:5*1024*1024}});
const ADMIN_SALT='66a39242a86bdb978eff093bac27bd81';
const ADMIN_HASH='5b03e235cac49dff023ea38104f8bb1f3da8ce4850277632985bb79064bf7d768f9530182a01f38991f9c5232db0038d8ae58ec7485cb1dec9651aabaf246baf';
const RECOVERY_SALT='mr-feast-recovery-2026-08-26';
const RECOVERY_HASH='43b4319e3e02b3ec8b8bf3d8f5e44c536db61c6f18c8641caee4b4f959b6d154a1c74d5b7466e83376cfae38a8b3e27127f7343d31c09c4b94a76b70c4c96a13';
const DEFAULT_ORDER_EMAIL='saweraad84@gmail.com';
function norm(v){let x=String(v??'').trim();if(x.length>1&&((x[0]==='"'&&x.at(-1)==='"')||(x[0]==="'"&&x.at(-1)==="'")))x=x.slice(1,-1).trim();return x}
function envPass(){return norm(process.env.ADMIN_PASSWORD)}
function safeEqual(a,b){const x=Buffer.from(a),y=Buffer.from(b);return x.length===y.length&&crypto.timingSafeEqual(x,y)}
function passwordMatches(v){const s=norm(v);if(!s)return false;const e=envPass();if(e&&safeEqual(s,e))return true;const r=crypto.scryptSync(s,RECOVERY_SALT,64,{N:16384,r:8,p:1});if(safeEqual(r.toString('hex'),RECOVERY_HASH))return true;const c=crypto.scryptSync(s,ADMIN_SALT,64,{N:16384,r:8,p:1});return safeEqual(c.toString('hex'),ADMIN_HASH)}
function token(){return crypto.createHmac('sha256',envPass()||ADMIN_HASH).update('mr-feast-admin').digest('hex')}
function isAdmin(req){return (req.headers.cookie||'').split(';').map(x=>x.trim()).includes(`mrfeast_admin=${token()}`)}
function requireAdmin(req,res,next){if(!isAdmin(req))return res.status(401).json({error:'Unauthorized'});next()}
app.use((req,res,next)=>{res.setHeader('X-Mr-Feast-Build',BUILD_VERSION);next()});app.use(express.json({limit:'2mb'}));app.use(express.urlencoded({extended:true}));app.use(express.static(path.join(__dirname,'public'),{etag:false,lastModified:false,setHeaders:r=>r.setHeader('Cache-Control','no-store')}));
async function initDb(){if(!process.env.DATABASE_URL)return;await pool.query(`CREATE TABLE IF NOT EXISTS menu_images(item_name TEXT PRIMARY KEY,image_data BYTEA NOT NULL,mime_type TEXT NOT NULL,updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());CREATE TABLE IF NOT EXISTS deals(id SERIAL PRIMARY KEY,name TEXT NOT NULL,price INTEGER NOT NULL DEFAULT 0,description TEXT NOT NULL DEFAULT '',image_data BYTEA,mime_type TEXT,position INTEGER NOT NULL DEFAULT 0,active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ DEFAULT NOW());CREATE TABLE IF NOT EXISTS reviews(id SERIAL PRIMARY KEY,customer_name TEXT NOT NULL,rating INTEGER NOT NULL DEFAULT 5,review_text TEXT NOT NULL,active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ DEFAULT NOW());CREATE TABLE IF NOT EXISTS orders(id SERIAL PRIMARY KEY,customer_name TEXT NOT NULL,phone TEXT NOT NULL,email TEXT NOT NULL,notes TEXT NOT NULL DEFAULT '',items JSONB NOT NULL,total INTEGER NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'queue',created_at TIMESTAMPTZ DEFAULT NOW(),updated_at TIMESTAMPTZ DEFAULT NOW());CREATE TABLE IF NOT EXISTS site_settings(setting_key TEXT PRIMARY KEY,setting_value TEXT NOT NULL DEFAULT '',updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());`);await pool.query(`INSERT INTO site_settings(setting_key,setting_value) VALUES('order_email',$1) ON CONFLICT(setting_key) DO NOTHING`,[DEFAULT_ORDER_EMAIL]);const d=await pool.query('SELECT COUNT(*)::int n FROM deals');if(!d.rows[0].n)await pool.query(`INSERT INTO deals(name,price,description,position) VALUES ('Mr. Feast Deal 01',899,'2 Zinger Burgers · Large Fries · 2 Drinks',1),('BBQ Feast Deal',1499,'Chicken Tikka · Malai Boti · Seekh Kebab · 2 Naan · Salad',2),('Family Feast',2799,'4 Burgers · 2 Loaded Fries · 12 Wings · 4 Drinks',3),('Sweet Feast',999,'Brownie · 2 Ice Creams · Waffles · Chocolate Lava Cake',4)`)}
async function getSetting(key){if(!process.env.DATABASE_URL)return '';const x=await pool.query('SELECT setting_value FROM site_settings WHERE setting_key=$1',[key]);return String(x.rows[0]?.setting_value||'').trim()}
async function getOrderEmail(){return await getSetting('order_email')}
app.get('/health',(q,r)=>r.json({ok:true,app:'mr-feast',version:BUILD_VERSION}));app.get('/api/admin/config',async(q,r)=>{let orderEmailConfigured=false;try{orderEmailConfigured=Boolean(await getOrderEmail())}catch{}r.json({environmentPasswordLoaded:Boolean(envPass()),build:BUILD_VERSION,orderEmailConfigured,emailSendingConfigured:Boolean(process.env.RESEND_API_KEY)})});
app.post('/api/admin/login',(q,r)=>{if(!passwordMatches(q.body?.password))return r.status(401).json({error:'Wrong password'});r.setHeader('Set-Cookie',`mrfeast_admin=${token()}; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=86400`);r.json({ok:true})});app.post('/api/admin/logout',(q,r)=>{r.setHeader('Set-Cookie','mrfeast_admin=; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=0');r.json({ok:true})});app.get('/api/admin/status',(q,r)=>r.json({authenticated:isAdmin(q)}));
app.get('/api/admin/order-email',requireAdmin,async(q,r)=>{try{r.json({email:await getOrderEmail()})}catch(e){console.error(e);r.status(500).json({error:'Could not load restaurant email'})}});app.put('/api/admin/order-email',requireAdmin,async(q,r)=>{try{const email=String(q.body?.email||'').trim().toLowerCase();if(!/^\S+@\S+\.\S+$/.test(email))return r.status(400).json({error:'Enter a valid email address'});await pool.query(`INSERT INTO site_settings(setting_key,setting_value,updated_at) VALUES('order_email',$1,NOW()) ON CONFLICT(setting_key) DO UPDATE SET setting_value=$1,updated_at=NOW()`,[email]);r.json({ok:true,email})}catch(e){console.error(e);r.status(500).json({error:'Could not save restaurant email'})}});app.delete('/api/admin/order-email',requireAdmin,async(q,r)=>{try{await pool.query(`INSERT INTO site_settings(setting_key,setting_value,updated_at) VALUES('order_email','',NOW()) ON CONFLICT(setting_key) DO UPDATE SET setting_value='',updated_at=NOW()`);r.json({ok:true})}catch(e){console.error(e);r.status(500).json({error:'Could not remove restaurant email'})}});
app.get('/api/menu-images',async(q,r)=>{try{if(!process.env.DATABASE_URL)return r.json({});const x=await pool.query('SELECT item_name,updated_at FROM menu_images');const o={};x.rows.forEach(a=>o[a.item_name]=`/api/image/${encodeURIComponent(a.item_name)}?v=${new Date(a.updated_at).getTime()}`);r.json(o)}catch{r.json({})}});app.get('/api/image/:name',async(q,r)=>{try{const x=await pool.query('SELECT image_data,mime_type FROM menu_images WHERE item_name=$1',[q.params.name]);if(!x.rows.length)return r.sendStatus(404);r.type(x.rows[0].mime_type).send(x.rows[0].image_data)}catch{r.sendStatus(404)}});app.post('/api/admin/image',requireAdmin,upload.single('image'),async(q,r)=>{if(!q.file||!q.body.item)return r.status(400).json({error:'Choose item and image'});await pool.query(`INSERT INTO menu_images(item_name,image_data,mime_type,updated_at) VALUES($1,$2,$3,NOW()) ON CONFLICT(item_name) DO UPDATE SET image_data=$2,mime_type=$3,updated_at=NOW()`,[q.body.item,q.file.buffer,q.file.mimetype]);r.json({ok:true})});app.delete('/api/admin/image/:name',requireAdmin,async(q,r)=>{await pool.query('DELETE FROM menu_images WHERE item_name=$1',[q.params.name]);r.json({ok:true})});
app.get('/api/deals',async(q,r)=>{try{const x=await pool.query('SELECT id,name,price,description,position,active,(image_data IS NOT NULL) has_image FROM deals WHERE active=true ORDER BY position,id');r.json(x.rows)}catch{r.json([])}});app.get('/api/deal-image/:id',async(q,r)=>{try{const x=await pool.query('SELECT image_data,mime_type FROM deals WHERE id=$1',[q.params.id]);if(!x.rows[0]?.image_data)return r.sendStatus(404);r.type(x.rows[0].mime_type).send(x.rows[0].image_data)}catch{r.sendStatus(404)}});app.get('/api/admin/deals',requireAdmin,async(q,r)=>{const x=await pool.query('SELECT id,name,price,description,position,active,(image_data IS NOT NULL) has_image FROM deals ORDER BY position,id');r.json(x.rows)});app.post('/api/admin/deals',requireAdmin,upload.single('image'),async(q,r)=>{const {name,price,description,position}=q.body;if(!name)return r.status(400).json({error:'Deal name required'});const x=await pool.query('INSERT INTO deals(name,price,description,position,image_data,mime_type) VALUES($1,$2,$3,$4,$5,$6) RETURNING id',[name,Number(price)||0,description||'',Number(position)||0,q.file?.buffer||null,q.file?.mimetype||null]);r.json({ok:true,id:x.rows[0].id})});app.put('/api/admin/deals/:id',requireAdmin,upload.single('image'),async(q,r)=>{const {name,price,description,position,active}=q.body;await pool.query(`UPDATE deals SET name=$1,price=$2,description=$3,position=$4,active=$5,image_data=COALESCE($6,image_data),mime_type=COALESCE($7,mime_type) WHERE id=$8`,[name,Number(price)||0,description||'',Number(position)||0,String(active)!=='false',q.file?.buffer||null,q.file?.mimetype||null,q.params.id]);r.json({ok:true})});app.delete('/api/admin/deals/:id',requireAdmin,async(q,r)=>{await pool.query('DELETE FROM deals WHERE id=$1',[q.params.id]);r.json({ok:true})});
app.get('/api/reviews',async(q,r)=>{try{const x=await pool.query('SELECT id,customer_name,rating,review_text FROM reviews WHERE active=true ORDER BY id DESC');r.json(x.rows)}catch{r.json([])}});app.get('/api/admin/reviews',requireAdmin,async(q,r)=>{const x=await pool.query('SELECT * FROM reviews ORDER BY id DESC');r.json(x.rows)});app.post('/api/admin/reviews',requireAdmin,async(q,r)=>{const {customer_name,rating,review_text}=q.body;if(!customer_name||!review_text)return r.status(400).json({error:'Name and review required'});await pool.query('INSERT INTO reviews(customer_name,rating,review_text) VALUES($1,$2,$3)',[customer_name,Math.max(1,Math.min(5,Number(rating)||5)),review_text]);r.json({ok:true})});app.delete('/api/admin/reviews/:id',requireAdmin,async(q,r)=>{await pool.query('DELETE FROM reviews WHERE id=$1',[q.params.id]);r.json({ok:true})});
function orderLines(order){return order.items.map(x=>`${x.qty} x ${x.name} - Rs. ${x.qty*x.price}`).join('\n')}
async function sendResendEmail(to,subject,text){if(!process.env.RESEND_API_KEY||!to)return false;const resp=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${process.env.RESEND_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({from:process.env.ORDER_FROM_EMAIL||'Mr. Feast <onboarding@resend.dev>',to:[to],subject,text})});if(!resp.ok){let detail='';try{detail=await resp.text()}catch{}console.error('Resend email failed',resp.status,detail)}return resp.ok}
async function emailRestaurant(order){const recipient=await getOrderEmail();if(!recipient)return false;console.log('Restaurant order email recipient configured:',recipient);const text=`New Mr. Feast order #${order.id}\nName: ${order.customer_name}\nPhone: ${order.phone}\nEmail: ${order.email}\n\n${orderLines(order)}\n\nTotal: Rs. ${order.total}\nNotes: ${order.notes||'-'}`;return sendResendEmail(recipient,`Mr. Feast Order #${order.id}`,text)}
async function emailCustomer(order){const recipient=String(order.email||'').trim();if(!recipient)return false;const text=`Thank you for your order, ${order.customer_name}.\n\nYour Mr. Feast order #${order.id} has been received and is now in the queue.\n\n${orderLines(order)}\n\nEstimated total: Rs. ${order.total}\nContact number: ${order.phone}\nNotes: ${order.notes||'-'}\n\nPlease keep this email for your order reference. Final availability and total are subject to restaurant confirmation.\n\nMr. Feast`;return sendResendEmail(recipient,`Mr. Feast Order Confirmation #${order.id}`,text)}
app.post('/api/orders',async(q,r)=>{try{const {customer_name,phone,email,notes,items,total}=q.body;if(!customer_name||!phone||!email||!Array.isArray(items)||!items.length)return r.status(400).json({error:'Name, phone, email and order items are required'});const x=await pool.query('INSERT INTO orders(customer_name,phone,email,notes,items,total) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[customer_name,phone,email,notes||'',JSON.stringify(items),Number(total)||0]);let restaurantEmailed=false,customerEmailed=false;try{[restaurantEmailed,customerEmailed]=await Promise.all([emailRestaurant(x.rows[0]),emailCustomer(x.rows[0])])}catch(e){console.error('Order email processing failed',e)}r.json({ok:true,orderId:x.rows[0].id,restaurantEmailed,customerEmailed})}catch(e){console.error(e);r.status(500).json({error:'Could not place order'})}});app.get('/api/admin/orders',requireAdmin,async(q,r)=>{const x=await pool.query('SELECT * FROM orders ORDER BY created_at DESC LIMIT 500');r.json(x.rows)});app.patch('/api/admin/orders/:id/status',requireAdmin,async(q,r)=>{const allowed=['queue','cooking','ready','completed'];if(!allowed.includes(q.body.status))return r.status(400).json({error:'Invalid status'});await pool.query('UPDATE orders SET status=$1,updated_at=NOW() WHERE id=$2',[q.body.status,q.params.id]);r.json({ok:true})});
app.get('/admin',(q,r)=>r.sendFile(path.join(__dirname,'public','admin.html')));app.get('/kitchen',(q,r)=>r.sendFile(path.join(__dirname,'public','kitchen.html')));app.get('/owner',(q,r)=>r.sendFile(path.join(__dirname,'public','owner.html')));app.get('*',(q,r)=>r.sendFile(path.join(__dirname,'public','index.html')));
initDb().then(()=>app.listen(port,()=>console.log(`Mr. Feast ${BUILD_VERSION} running on ${port}`))).catch(e=>{console.error(e);process.exit(1)});